name: ESLint

on: [ push ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Run ESLint
        run: |
          npm install
          npm run eslint